DROP DATABASE EJERCICIO2_TEST;
CREATE DATABASE EJERCICIO2_TEST;
USE EJERCICIO2_TEST;

CREATE TABLE IF NOT EXISTS RECINTOS(
    COD_RECINTO INT NOT NULL,
    NOMBRE VARCHAR(15) NOT NULL,
    DIRECCION VARCHAR(40) NOT NULL,
    CIUDAD VARCHAR(10) NOT NULL,
    TELEFONO INT NOT NULL,
    HORARIO VARCHAR(10) NOT NULL,
    CONSTRAINT PK PRIMARY KEY (COD_RECINTO)
);

CREATE TABLE IF NOT EXISTS ASIENTOS(
    COD_RECINTO INT NOT NULL,
    ZONA INT NOT NULL,
    FILA INT NOT NULL,
    NUMERO INT NOT NULL,
    CONSTRAINT PK PRIMARY KEY (COD_RECINTO,ZONA,FILA,NUMERO),
    CONSTRAINT FK_CODRECINTO1 FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS (COD_RECINTO)
);



CREATE TABLE IF NOT EXISTS ZONAS_RECINTOS(
    COD_RECINTO INT NOT NULL,
    ZONA INT NOT NULL,
    CAPACIDAD INT NOT NULL,
    CONSTRAINT PK PRIMARY KEY (COD_RECINTO,ZONA),
    CONSTRAINT FK_CODRECINTO2 FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS (COD_RECINTO),
    CONSTRAINT FK_ZONA FOREIGN KEY (ZONA) REFERENCES ASIENTOS (ZONA)
);



CREATE TABLE IF NOT EXISTS ESPECTACULOS(
    COD_ESPECTACULO INT NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    TIPO VARCHAR(10) NOT NULL,
    FECHA_INICIAL DATE NOT NULL,
    FECHA_FINAL DATE NOT NULL,
    INTERPRETE CHAR(10) NOT NULL,
    COD_RECINTO INT NOT NULL,
    CONSTRAINT PK PRIMARY KEY (COD_ESPECTACULO,COD_RECINTO),
    CONSTRAINT FK_ESPECTACULOS1 FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS (COD_RECINTO)
);

CREATE TABLE IF NOT EXISTS REPRESENTACIONES(
    COD_ESPECTACULO INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    CONSTRAINT PK PRIMARY KEY (COD_ESPECTACULO,FECHA,HORA),
    CONSTRAINT FK_ESPECTACULOS2 FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO)
);

CREATE TABLE IF NOT EXISTS PRECIOS_ESPECTACULOS(
    COD_ESPECTACULO INT NOT NULL,
    COD_RECINTO INT NOT NULL,
    ZONA INT NOT NULL,
    PRECIO REAL NOT NULL,
    CONSTRAINT PK PRIMARY KEY (COD_ESPECTACULO,COD_RECINTO,ZONA),
    CONSTRAINT FK_ESPECTACULOS3 FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS (COD_ESPECTACULO),
    CONSTRAINT FK_CODRECINTO3 FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS (COD_RECINTO)

);

CREATE TABLE IF NOT EXISTS ENTRADAS(
    COD_ESPECTACULO INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    COD_RECINTO INT NOT NULL,
    FILA INT NOT NULL,
    NUMERO INT NOT NULL,
    ZONA INT NOT NULL,
    DNI_CLIENTE CHAR(9) NOT NULL,
    CONSTRAINT PK PRIMARY KEY (COD_ESPECTACULO,FECHA,HORA,FILA,NUMERO,ZONA,DNI_CLIENTE),
    CONSTRAINT FK_ESPECTACULOS4 FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS (COD_ESPECTACULO),
    CONSTRAINT FK_CODRECINTO4 FOREIGN KEY (COD_RECINTO) REFERENCES ASIENTOS (COD_RECINTO),
    CONSTRAINT FK_DNICLIENTE1 FOREIGN KEY (DNI_CLIENTE) REFERENCES ESPECTADORES (DNI_CLIENTE)
);

CREATE TABLE IF NOT EXISTS ESPECTADORES(
    DNI_CLIENTE CHAR(9) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(40) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    CIUDAD VARCHAR(10) NOT NULL,
    NTARJETA INT NOT NULL,
    CONSTRAINT PK PRIMARY KEY (DNI_CLIENTE)
);